---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "depth_analysis_of_samples"
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::matplotlib=3.8.4
- conda-forge::numpy=2.0.0rc1
- conda-forge::pandas=2.2.2
- conda-forge::python=3.12.3