---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "depth_analysis_of_samples"
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::python=3.12.3
- pip
- pip:
  - matplotlib==3.9.0rc2
  - numpy==2.0.0rc1
  - pandas==2.2.0rc0