name: Publish Image Using Sha and Timestamp

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Publish Image using commit sha and timestamp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/qc-pipeline-python
          location: containers/python
          dockerfile: containers/python/Dockerfile
          tag_format: "{sha}-{timestamp}"